### ISSUE TITLE
好像修改config成5.0.驱动，实际编译出来还是4.4的驱动

### ISSUE THREAD

**Issue by sdf8057** [chongshengB/rt-n56u-old#2]

**Comment by zhuwenbing** [comment]
看下是不是编译的时候配置文件没选对（或者改错配置文件了）？文档上写明了的
> sudo ./build_firmware_modify K2P
> #脚本第一个参数为路由型号，在trunk/configs/templates/中

如果修改的是/trunk/.config应该是无效的。
